version: '3'
services:
  redis:
    image: redis
  
  plugin_service:
    build:
      context: ./plugin_service
      dockerfile: ./Dockerfile
    tty: true
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - DEFAULT_URL=http://127.0.0.1:8888
      # - PERMANENT_CHANNEL=a5100bcd-3b33-48dc-a8b0-67f88182f24e
    depends_on:
      - redis
    volumes:
      - ./plugin_service:/app
      - ./service.py:/opt/conda/lib/python3.7/site-packages/nanome/service.py
      - ./interface.py:/opt/conda/lib/python3.7/site-packages/nanome/interface.py
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -r -v
  
  cookbook:
    build:
      context: ./cookbook
      dockerfile: ./Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - ./cookbook:/app
      - ./service.py:/opt/conda/lib/python3.9/site-packages/nanome/service.py
      - ./interface.py:/opt/conda/lib/python3.9/site-packages/nanome/interface.py

    tty: true
    stdin_open: true
    depends_on:
      - redis
  # Required for Neo4j integration notebook. 
  # neo4j:
  #   image: neo4j
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - $HOME/neo4j/data:/data