version: '3'
services:
  redis:
    image: redis
  redis_plugin:
    tty: true
    image: redispubsub:latest  # public.ecr.aws/h7r1e4h2/cookbook-redis-service:0.2.2
    environment:
      - DEFAULT_URL=http://127.0.0.1:8888
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - NTS_HOST=${NTS_HOST:-}
      - NTS_PORT=${NTS_PORT:-}
      - NTS_KEY=${NTS_KEY:-}
      - ARGS=${ARGS:-}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-change_me}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-}
      - PLUGIN_NAME=${PLUGIN_NAME:-}

    depends_on:
      - redis
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -r -v
  
  cookbook:
    build:
      context: .
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-change_me}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-}
      - NTS_HOST=${NTS_HOST:-}
      - NTS_PORT=${NTS_PORT:-}
      - NTS_KEY=${NTS_KEY:-}
    ports:
      - 8888:8888
    volumes:
      - ./cookbook:/app/cookbook
      - ./redis-interface:/app/redis-interface
    tty: true
    stdin_open: true
    depends_on:
      - redis
