version: '3'
services:
  redis:
    image: redis
  redis_plugin:
    tty: true
    image: public.ecr.aws/h7r1e4h2/cookbook-redis-service:1.0.1
    environment:
      # - DEFAULT_URL=http://127.0.0.1:8888
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - NTS_HOST=${NTS_HOST:-}
      - NTS_PORT=${NTS_PORT:-}
      - NTS_KEY=${NTS_KEY:-}
      - ARGS=${ARGS:-}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-abc}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-}
      - PLUGIN_NAME=[wip]-Cookbook
      - PLUGIN_VERBOSE=${PLUGIN_VERBOSE:-true}
    depends_on:
      - redis
  
  cookbook:
    build:
      context: .
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-abc}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-}
    ports:
      - 8888:8888
    volumes:
      - ./cookbook:/app/cookbook
    tty: true
    stdin_open: true
    depends_on:
      - redis
