version: '3'
services:
  redis:
    image: redis
  plugin_service:
    build:
      context: ./plugin_service
      dockerfile: ./Dockerfile
    tty: true
    environment:
      - DEFAULT_URL=http://127.0.0.1:8888
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - NTS_HOST=${NTS_HOST:-}
      - NTS_PORT=${NTS_PORT:-}
      - NTS_KEY=${NTS_KEY:-}
      - ARGS=${ARGS:-}
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-change_me}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-}

    depends_on:
      - redis
    volumes:
      - ./plugin_service:/app
      # - /home/mike/workspace/nanome-lib/nanome:/opt/conda/lib/python3.7/site-packages/nanome
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -r -v
  
  cookbook:
    build:
      context: ./cookbook
      dockerfile: ./Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-change_me}
      - REDIS_CHANNEL=${REDIS_CHANNEL:-}
    ports:
      - 8888:8888
    volumes:
      - ./cookbook:/app
      # - /home/mike/workspace/nanome-lib/nanome:/opt/conda/lib/python3.9/site-packages/nanome

    tty: true
    stdin_open: true
    depends_on:
      - redis
  # Uncomment to use Neo4j integration notebook. 
  # neo4j:
  #   image: neo4j
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   volumes:
  #     - $HOME/neo4j/data:/data