name: Unittests
on:
  pull_request:
    branches: [ main ]

jobs:
  unittests:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install -r requirements.txt
    - run: conda env update -f arpeggio_environ.yml
    - run: python run_tests.py
